#!/bin/sh
# this script is supposed to be executed as root
log=/var/log/paster-ckan
pidfile=/var/run/ckan-dev.pid
exec 0>/dev/null >$log 2>&1
sudo -u ckan -s paster-ckan2 
until grep "%%PID%%" >/dev/null $log
do
  sleep 1 
done
grep "%%PID%%" $log | sed "s/%%PID%% //" >$pidfile
